/*
 * Copyright (2025) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.delta.workload.tables

import io.delta.workload.WorkloadTestSuite

class IdentityColumnsSuite extends WorkloadTestSuite("identity_columns") {

  test("ic_001_various_config") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 100),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (10)")
    sql("INSERT INTO tbl (value) VALUES (20)")
    sql("INSERT INTO tbl (value) VALUES (30)")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "id >= 1000 AND id <= 1200")
    read(t, columns = Seq("id"))
    snapshot(t)
  }

  test("ic_002_default_config") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (100)")
    sql("INSERT INTO tbl (value) VALUES (200)")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "id = 1")
    snapshot(t)
  }

  test("ic_003_multiple_identity_cols") {
    sql("""CREATE TABLE tbl (
      id1 LONG GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      id2 LONG GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY -10),
      value STRING
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (id1, id2, value) VALUES (1, 100, 'a')")
    sql("INSERT INTO tbl (value) VALUES ('b')")
    sql("INSERT INTO tbl (id1, value) VALUES (2, 'c')")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "id2 < 100")
    read(t, columns = Seq("id1", "id2"))
    snapshot(t)
  }

  test("ic_004_with_generated_col") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),
      id_plus_one LONG GENERATED ALWAYS AS (id + 1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (10)")
    sql("INSERT INTO tbl (value) VALUES (20)")
    val t = registerTable("tbl")
    read(t)
    read(t, columns = Seq("id", "id_plus_one"))
    snapshot(t)
  }

  test("ic_005_identity_not_exposed") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      part LONG,
      value INT
    ) USING delta PARTITIONED BY (part)
      TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (id, part, value) VALUES (1, 1, 10)")
    sql("INSERT INTO tbl (part, value) VALUES (2, 20)")
    sql("INSERT INTO tbl (id, part, value) VALUES (3, 1, 30)")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "part = 1")
    read(t, columns = Seq("id", "part", "value"))
    snapshot(t)
  }

  test("ic_006_ctas_no_inherit") {
    sql("""CREATE TABLE src (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO src (value) VALUES (10)")
    sql("""CREATE TABLE tbl USING delta
      TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')
      AS SELECT * FROM src""")
    val t = registerTable("tbl")
    read(t)
    read(t, columns = Seq("id"))
    snapshot(t)
  }

  test("ic_007_replace_resets_watermark") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (1)")
    sql("INSERT INTO tbl (value) VALUES (2)")
    sql("""CREATE OR REPLACE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 5000 INCREMENT BY 1),
      value STRING
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES ('new')")
    val t = registerTable("tbl")
    read(t)
    read(t, version = 2)
    val N = 4L
    for (v <- 0L to N) snapshot(t, version = v)
  }

  test("ic_008_restore_positive_step") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 0 INCREMENT BY 1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    for (i <- 1 to 6) sql(s"INSERT INTO tbl (value) VALUES ($i)")
    sql("RESTORE TABLE tbl TO VERSION AS OF 3")
    sql("INSERT INTO tbl (value) VALUES (99)")
    val t = registerTable("tbl")
    read(t)
    read(t, version = 3)
    val N = 8L
    for (v <- 0L to N) snapshot(t, version = v)
  }

  test("ic_009_restore_negative_step") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 0 INCREMENT BY -1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    for (i <- 1 to 6) sql(s"INSERT INTO tbl (value) VALUES ($i)")
    sql("RESTORE TABLE tbl TO VERSION AS OF 3")
    sql("INSERT INTO tbl (value) VALUES (99)")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "id < 0")
    val N = 8L
    for (v <- 0L to N) snapshot(t, version = v)
  }

  test("ic_010_restore_partitioned") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
      value INT
    ) USING delta PARTITIONED BY (value)
      TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (1),(2)")
    sql("INSERT INTO tbl (value) VALUES (3),(4)")
    sql("RESTORE TABLE tbl TO VERSION AS OF 1")
    sql("INSERT INTO tbl (value) VALUES (5),(6)")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "value = 1")
    read(t, version = 1)
    val N = 4L
    for (v <- 0L to N) snapshot(t, version = v)
  }

  test("ic_011_generated_by_default") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (10)")
    sql("INSERT INTO tbl (id, value) VALUES (999, 20)")
    sql("INSERT INTO tbl (value) VALUES (30)")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "id = 999")
    snapshot(t)
  }

  test("ic_012_time_travel") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (10)")
    sql("INSERT INTO tbl (value) VALUES (20)")
    sql("INSERT INTO tbl (value) VALUES (30)")
    val t = registerTable("tbl")
    read(t)
    read(t, version = 1)
    read(t, version = 2)
    val N = 3L
    for (v <- 0L to N) snapshot(t, version = v)
  }

  test("ic_013_column_mapping") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      name STRING
    ) USING delta TBLPROPERTIES (
      'delta.columnMapping.mode' = 'name',
      'delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (name) VALUES ('alice')")
    sql("INSERT INTO tbl (name) VALUES ('bob')")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "name = 'alice'")
    snapshot(t)
  }

  test("ic_014_delete") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (1)")
    sql("INSERT INTO tbl (value) VALUES (2)")
    sql("DELETE FROM tbl WHERE value = 1")
    sql("INSERT INTO tbl (value) VALUES (3)")
    val t = registerTable("tbl")
    read(t)
    read(t, version = 2)
    val N = 4L
    for (v <- 0L to N) snapshot(t, version = v)
  }

  test("ic_015_merge") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 2),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (10),(20),(30)")
    sql("CREATE TABLE src (value INT) USING delta")
    sql("INSERT INTO src VALUES (20),(40)")
    sql("""MERGE INTO tbl t USING src s ON t.value = s.value
      WHEN MATCHED THEN UPDATE SET value = s.value * 10
      WHEN NOT MATCHED THEN INSERT (value) VALUES (s.value)""")
    val t = registerTable("tbl")
    read(t)
    read(t, version = 1)
    val N = 2L
    for (v <- 0L to N) snapshot(t, version = v)
  }

  test("ic_016_update") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 0 INCREMENT BY 1),
      value INT
    ) USING delta TBLPROPERTIES (
      'delta.enableChangeDataFeed' = 'true',
      'delta.enableDeletionVectors' = 'true')""")
    for (i <- 1 to 6) sql(s"INSERT INTO tbl (value) VALUES (${i * 10})")
    sql("UPDATE tbl SET value = value + 100 WHERE id < 3")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "value >= 100")
    read(t, version = 6)
    val N = 7L
    for (v <- 0L to N) snapshot(t, version = v)
  }

  test("ic_bigint_type") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) SELECT CAST(id AS INT) FROM range(100)")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "value >= 50")
    snapshot(t)
  }

  test("ic_negative_step") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY -1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (10),(20),(30)")
    val t = registerTable("tbl")
    read(t)
    snapshot(t)
  }

  test("ic_partitioned") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT,
      category STRING
    ) USING delta PARTITIONED BY (category)
      TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value, category) VALUES (10,'A'),(20,'B'),(30,'A'),(40,'B'),(50,'A')")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "category = 'A'")
    read(t, predicate = "category = 'B'")
    snapshot(t)
  }

  test("ic_with_schema_evolution") {
    sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    sql("INSERT INTO tbl (value) VALUES (10),(20)")
    sql("ALTER TABLE tbl ADD COLUMN (extra STRING)")
    sql("INSERT INTO tbl (value, extra) VALUES (30, 'hello'),(40, 'world')")
    val t = registerTable("tbl")
    read(t)
    read(t, predicate = "extra IS NOT NULL")
    read(t, version = 1)
    val N = 3L
    for (v <- 0L to N) snapshot(t, version = v)
  }

}
