/**
 * Legacy dsRead* and dse* workloads.
 * These reproduce the exact tables and specs from acceptance_workloads/ directories
 * that were generated by the original DeltaSuite-based capture system.
 *
 * Run: ./bin/generate-workload.sh tables/core_reads_legacy.scala
 */
import io.delta.workload.WorkloadGenerator._

// ---------------------------------------------------------------------------
// dsReadAfterOptimize: 10 single-row appends then OPTIMIZE (DVs enabled)
// ---------------------------------------------------------------------------
workload("dsReadAfterOptimize", "Read after OPTIMIZE") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  (1 to 10).foreach { i =>
    w.sql(s"INSERT INTO tbl VALUES ($i)")
  }
  w.sql("OPTIMIZE tbl")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadAndPredicate: compound AND predicate
// ---------------------------------------------------------------------------
workload("dsReadAndPredicate", "Read with AND predicate") { w =>
  w.sql("""CREATE TABLE tbl (id INT, cat STRING, score INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'a',10),(2,'b',20),(3,'a',30),(4,'b',10),(5,'a',20)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "cat = 'a' AND score > 15")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadAppend: two appends
// ---------------------------------------------------------------------------
workload("dsReadAppend", "Read after append") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 6)")
  w.sql("INSERT INTO tbl SELECT id FROM range(6, 11)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadArrayColumn: array columns
// ---------------------------------------------------------------------------
workload("dsReadArrayColumn", "Array columns") { w =>
  w.sql("""CREATE TABLE tbl (id INT, tags ARRAY<STRING>, scores ARRAY<INT>) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, array('a','b','c'), array(10,20,30))")
  w.sql("INSERT INTO tbl VALUES (2, array('x'), array(99))")
  w.sql("INSERT INTO tbl VALUES (3, array(), array())")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadBadProtocol: error on unsupported reader version
// ---------------------------------------------------------------------------
workload("dsReadBadProtocol", "Error: unsupported reader version", "error") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1),(2),(3)")
  val t = w.table("tbl")
  // Bump minReaderVersion to an unsupported value
  w.mutateTable(t) { dir =>
    import scala.collection.JavaConverters._
    val mapper = new com.fasterxml.jackson.databind.ObjectMapper()
    val commitFile = dir.resolve("_delta_log/00000000000000000000.json")
    val lines = java.nio.file.Files.readAllLines(commitFile).asScala
    val newLines = lines.map { line =>
      if (line.contains("\"protocol\"")) {
        val node = mapper.readTree(line)
        val proto = node.get("protocol").asInstanceOf[com.fasterxml.jackson.databind.node.ObjectNode]
        proto.put("minReaderVersion", 99)
        mapper.writeValueAsString(node)
      } else line
    }
    java.nio.file.Files.write(commitFile, newLines.asJava)
  }
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadBasic: simple 10-row table
// ---------------------------------------------------------------------------
workload("dsReadBasic", "Basic read") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 11)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadBetweenPredicate: BETWEEN filter
// ---------------------------------------------------------------------------
workload("dsReadBetweenPredicate", "Read with BETWEEN predicate") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 21)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "value BETWEEN 5 AND 15")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadBinaryType: binary column
// ---------------------------------------------------------------------------
workload("dsReadBinaryType", "Binary type") { w =>
  w.sql("""CREATE TABLE tbl (id INT, data BINARY) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, X'48454C4C4F')")
  w.sql("INSERT INTO tbl VALUES (2, X'574F524C44')")
  w.sql("INSERT INTO tbl VALUES (3, X'')")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadBooleanFilter: boolean column with true/false filters
// ---------------------------------------------------------------------------
workload("dsReadBooleanFilter", "Boolean filter") { w =>
  w.sql("""CREATE TABLE tbl (id INT, active BOOLEAN) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, true)")
  w.sql("INSERT INTO tbl VALUES (2, false)")
  w.sql("INSERT INTO tbl VALUES (3, true)")
  w.sql("INSERT INTO tbl VALUES (4, false)")
  w.sql("INSERT INTO tbl VALUES (5, true)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "active = true")
  w.read(t, predicate = "active = false")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadCaseSensitive: mixed-case column names
// ---------------------------------------------------------------------------
workload("dsReadCaseSensitive", "Case-sensitive column names") { w =>
  w.sql("""CREATE TABLE tbl (Id INT, FirstName STRING, lastName STRING, AGE INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, 'Alice', 'Smith', 30)")
  w.sql("INSERT INTO tbl VALUES (2, 'Bob', 'Jones', 25)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadDateType: date column with filter
// ---------------------------------------------------------------------------
workload("dsReadDateType", "Date type with filter") { w =>
  w.sql("""CREATE TABLE tbl (id INT, event_date DATE) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, DATE'2024-01-01')")
  w.sql("INSERT INTO tbl VALUES (2, DATE'2024-06-15')")
  w.sql("INSERT INTO tbl VALUES (3, DATE'2024-12-31')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "event_date > DATE'2024-06-01'")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadDecimalType: decimal columns
// ---------------------------------------------------------------------------
workload("dsReadDecimalType", "Decimal type") { w =>
  w.sql("""CREATE TABLE tbl (id INT, price DECIMAL(10,2), ratio DECIMAL(18,8)) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, 99.99, 0.12345678)")
  w.sql("INSERT INTO tbl VALUES (2, 1234.56, 3.14159265)")
  w.sql("INSERT INTO tbl VALUES (3, 0.01, 0.00000001)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "price > 100")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadDeleteThenRead: DELETE then read
// ---------------------------------------------------------------------------
workload("dsReadDeleteThenRead", "Read after DELETE") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 11)")
  w.sql("DELETE FROM tbl WHERE value <= 3")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadDoubleType: double values including extreme
// ---------------------------------------------------------------------------
workload("dsReadDoubleType", "Double type") { w =>
  w.sql("""CREATE TABLE tbl (id INT, dval DOUBLE) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, 3.14159265358979), (2, -0.001), (3, 1.7976931348623157E308), (4, 0.0)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadEmptyPartition: partitioned table, filter on non-existent partition
// ---------------------------------------------------------------------------
workload("dsReadEmptyPartition", "Empty partition filter result") { w =>
  w.sql("""CREATE TABLE tbl (id BIGINT, part INT) USING delta
    PARTITIONED BY (part)
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id, CAST(id % 3 AS INT) FROM range(50)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "part = 99")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadEmptyString: error - no delta table at path
// ---------------------------------------------------------------------------
workload("dsReadEmptyString", "Error: no delta table at empty subdir", "error") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1)")
  val t = w.table("tbl")
  // Delete the delta log to simulate missing table
  w.mutateTable(t) { dir =>
    val logDir = dir.resolve("_delta_log")
    if (java.nio.file.Files.exists(logDir)) {
      java.nio.file.Files.walk(logDir).sorted(java.util.Comparator.reverseOrder())
        .forEach(p => java.nio.file.Files.deleteIfExists(p))
    }
  }
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadEmptyTable: error - no delta table at path
// ---------------------------------------------------------------------------
workload("dsReadEmptyTable", "Error: no delta table", "error") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1)")
  val t = w.table("tbl")
  w.mutateTable(t) { dir =>
    val logDir = dir.resolve("_delta_log")
    if (java.nio.file.Files.exists(logDir)) {
      java.nio.file.Files.walk(logDir).sorted(java.util.Comparator.reverseOrder())
        .forEach(p => java.nio.file.Files.deleteIfExists(p))
    }
  }
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadFloatType: float values including extreme
// ---------------------------------------------------------------------------
workload("dsReadFloatType", "Float type") { w =>
  w.sql("""CREATE TABLE tbl (id INT, fval FLOAT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, CAST(1.5 AS FLOAT)), (2, CAST(-2.5 AS FLOAT)), (3, CAST(0.0 AS FLOAT)), (4, CAST(3.4028235E38 AS FLOAT))")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadInPredicate: IN predicate
// ---------------------------------------------------------------------------
workload("dsReadInPredicate", "Read with IN predicate") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 21)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "value IN (1, 5, 10, 15, 20)")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadIsNotNullPredicate: IS NOT NULL filter
// ---------------------------------------------------------------------------
workload("dsReadIsNotNullPredicate", "IS NOT NULL predicate") { w =>
  w.sql("""CREATE TABLE tbl (id INT, label STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'a'),(NULL,'b'),(3,'c'),(NULL,'d'),(5,'e')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "id IS NOT NULL")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadIsNullPredicate: IS NULL filter
// ---------------------------------------------------------------------------
workload("dsReadIsNullPredicate", "IS NULL predicate") { w =>
  w.sql("""CREATE TABLE tbl (id INT, label STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'a'),(NULL,'b'),(3,'c'),(NULL,'d'),(5,'e')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "id IS NULL")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadLargeSchema: 25-column table (id + 24 computed cols)
// ---------------------------------------------------------------------------
workload("dsReadLargeSchema", "25 columns") { w =>
  val colDefs = (1 to 24).map(i => s"col_$i BIGINT").mkString(", ")
  w.sql(s"""CREATE TABLE tbl (id BIGINT, $colDefs) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  val colExprs = (1 to 24).map(i => s"id * $i AS col_$i").mkString(", ")
  w.sql(s"INSERT INTO tbl SELECT id, $colExprs FROM range(5)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadLikePredicate: LIKE filter
// ---------------------------------------------------------------------------
workload("dsReadLikePredicate", "LIKE predicate") { w =>
  w.sql("""CREATE TABLE tbl (id INT, word STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'alpha'),(2,'beta'),(3,'alphabet'),(4,'gamma'),(5,'alpine')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "word LIKE 'alp%'")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadLongType: long values including min/max
// ---------------------------------------------------------------------------
workload("dsReadLongType", "Long type") { w =>
  w.sql("""CREATE TABLE tbl (lval BIGINT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1),(9223372036854775807),(-9223372036854775808),(0),(9876543210)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadMapColumn: map columns
// ---------------------------------------------------------------------------
workload("dsReadMapColumn", "Map columns") { w =>
  w.sql("""CREATE TABLE tbl (id INT, props MAP<STRING, STRING>) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, map('color','red','size','large'))")
  w.sql("INSERT INTO tbl VALUES (2, map('color','blue'))")
  w.sql("INSERT INTO tbl VALUES (3, map())")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadMergeThenRead: MERGE then read
// ---------------------------------------------------------------------------
workload("dsReadMergeThenRead", "Read after MERGE") { w =>
  w.sql("""CREATE TABLE target (id INT, val STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO target VALUES (1,'a'),(2,'b'),(3,'c')")
  w.sql("""CREATE TABLE src (id INT, val STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO src VALUES (2,'updated'),(4,'new')")
  w.sql("""MERGE INTO target t USING src s ON t.id = s.id
    WHEN MATCHED THEN UPDATE SET val = s.val
    WHEN NOT MATCHED THEN INSERT *""")
  val t = w.table("target")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadMultiPartition: multiple partition columns
// ---------------------------------------------------------------------------
workload("dsReadMultiPartition", "Multiple partition columns") { w =>
  w.sql("""CREATE TABLE tbl (id INT, country STRING, city STRING, amount INT) USING delta
    PARTITIONED BY (country, city)
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'US','NY',100),(2,'US','CA',200),(3,'UK','LON',150),(4,'UK','MAN',120),(5,'US','NY',300)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "country = 'US'")
  w.read(t, predicate = "country = 'US' AND city = 'NY'")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadMultipleAppends: 7 single-row appends
// ---------------------------------------------------------------------------
workload("dsReadMultipleAppends", "Multiple appends") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  (1 to 7).foreach { i =>
    w.sql(s"INSERT INTO tbl VALUES ($i)")
  }
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadMultipleTypes: multiple data types in one table
// ---------------------------------------------------------------------------
workload("dsReadMultipleTypes", "Multiple data types") { w =>
  w.sql("""CREATE TABLE tbl (
    id INT, name STRING, score DOUBLE, active BOOLEAN,
    created DATE, updated TIMESTAMP
  ) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'alice',95.5,true,DATE'2024-01-01',TIMESTAMP'2024-01-01 10:00:00')")
  w.sql("INSERT INTO tbl VALUES (2,'bob',82.3,false,DATE'2024-02-15',TIMESTAMP'2024-02-15 14:30:00')")
  w.sql("INSERT INTO tbl VALUES (3,'charlie',91.0,true,DATE'2024-03-20',TIMESTAMP'2024-03-20 08:15:00')")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadNestedStruct: nested struct columns
// ---------------------------------------------------------------------------
workload("dsReadNestedStruct", "Nested struct columns") { w =>
  w.sql("""CREATE TABLE tbl (
    id INT, info STRUCT<name: STRING, age: INT, address: STRUCT<city: STRING, zip: STRING>>
  ) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, named_struct('name','alice','age',30,'address',named_struct('city','NYC','zip','10001')))")
  w.sql("INSERT INTO tbl VALUES (2, named_struct('name','bob','age',25,'address',named_struct('city','LA','zip','90001')))")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadNotEqualPredicate: != filter
// ---------------------------------------------------------------------------
workload("dsReadNotEqualPredicate", "Not equal predicate") { w =>
  w.sql("""CREATE TABLE tbl (id INT, cat STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'a'),(2,'b'),(3,'c'),(4,'a'),(5,'d')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "cat != 'a'")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadNullValues: null values across types
// ---------------------------------------------------------------------------
workload("dsReadNullValues", "Null values across types") { w =>
  w.sql("""CREATE TABLE tbl (id INT, name STRING, score DOUBLE, active BOOLEAN) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'alice',95.5,true)")
  w.sql("INSERT INTO tbl VALUES (2,null,null,null)")
  w.sql("INSERT INTO tbl VALUES (null,'charlie',88.0,false)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "name IS NOT NULL")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadOrPredicate: OR predicate
// ---------------------------------------------------------------------------
workload("dsReadOrPredicate", "OR predicate") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 11)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "id = 1 OR id = 5 OR id = 10")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadOverwrite: overwrite table
// ---------------------------------------------------------------------------
workload("dsReadOverwrite", "Read after overwrite") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 11)")
  w.sql("INSERT OVERWRITE tbl SELECT id FROM range(100, 106)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadPartitioned: partitioned table with filters
// ---------------------------------------------------------------------------
workload("dsReadPartitioned", "Partitioned read with filter") { w =>
  w.sql("""CREATE TABLE tbl (id BIGINT, part INT) USING delta
    PARTITIONED BY (part)
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id, CAST(id % 5 AS INT) FROM range(100)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "part = 0")
  w.read(t, predicate = "part = 3")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadPathWithSpaces: error - path with spaces (no delta log)
// ---------------------------------------------------------------------------
workload("dsReadPathWithSpaces", "Error: path with spaces", "error") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1)")
  val t = w.table("tbl")
  w.mutateTable(t) { dir =>
    val logDir = dir.resolve("_delta_log")
    if (java.nio.file.Files.exists(logDir)) {
      java.nio.file.Files.walk(logDir).sorted(java.util.Comparator.reverseOrder())
        .forEach(p => java.nio.file.Files.deleteIfExists(p))
    }
  }
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSaveMode: ErrorIfExists then Append
// ---------------------------------------------------------------------------
workload("dsReadSaveMode", "Save mode Append") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1),(2),(3)")
  w.sql("INSERT INTO tbl VALUES (4),(5)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSaveModeErrorIfExists: single write
// ---------------------------------------------------------------------------
workload("dsReadSaveModeErrorIfExists", "Save mode ErrorIfExists") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1),(2),(3)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSaveModeIgnore: write then ignore
// ---------------------------------------------------------------------------
workload("dsReadSaveModeIgnore", "Save mode Ignore") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1),(2),(3)")
  // Second write is Ignore mode - table already exists, so data is NOT written
  // The result is still just the original 3 rows
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSaveModeOverwrite: write then overwrite
// ---------------------------------------------------------------------------
workload("dsReadSaveModeOverwrite", "Save mode Overwrite") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1),(2),(3)")
  w.sql("INSERT OVERWRITE tbl VALUES (10),(20)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSchemaEvolution: ADD COLUMN then insert
// ---------------------------------------------------------------------------
workload("dsReadSchemaEvolution", "Schema evolution with ADD COLUMN") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 6)")
  w.sql("ALTER TABLE tbl ADD COLUMN name STRING")
  w.sql("INSERT INTO tbl VALUES (6,'alice')")
  w.sql("INSERT INTO tbl VALUES (7,'bob')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "name IS NOT NULL")
  w.snapshot(t, version = 0)
  w.snapshot(t, version = 1)
  w.snapshot(t, version = 2)
  w.snapshot(t, version = 3)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSelectColumns: column projection
// ---------------------------------------------------------------------------
workload("dsReadSelectColumns", "Column projection") { w =>
  w.sql("""CREATE TABLE tbl (id INT, name STRING, score DOUBLE, category STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'alice',95.5,'A')")
  w.sql("INSERT INTO tbl VALUES (2,'bob',82.3,'B')")
  w.sql("INSERT INTO tbl VALUES (3,'charlie',91.0,'A')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, columns = Seq("id", "name"))
  w.read(t, columns = Seq("score"))
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSnapshot: time travel read at versions
// ---------------------------------------------------------------------------
workload("dsReadSnapshot", "Time travel snapshot read") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 11)")
  w.sql("INSERT INTO tbl SELECT id FROM range(11, 21)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, version = 0)
  w.read(t, version = 1)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSnapshotPartitioned: partitioned snapshot read
// ---------------------------------------------------------------------------
workload("dsReadSnapshotPartitioned", "Partitioned snapshot read") { w =>
  w.sql("""CREATE TABLE tbl (region STRING, category INT, amount INT) USING delta
    PARTITIONED BY (region, category)
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES ('a',1,100),('b',2,200),('a',2,300)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSnapshotWithProperties: table with custom properties
// ---------------------------------------------------------------------------
workload("dsReadSnapshotWithProperties", "Snapshot with table properties") { w =>
  w.sql("""CREATE TABLE tbl (id INT, value STRING) USING delta
    TBLPROPERTIES (
      'delta.enableDeletionVectors' = 'true',
      'delta.logRetentionDuration' = 'interval 60 days',
      'delta.deletedFileRetentionDuration' = 'interval 30 days'
    )""")
  w.sql("INSERT INTO tbl VALUES (1,'a'),(2,'b'),(3,'c')")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadSpecialChars: special chars in partition values
// ---------------------------------------------------------------------------
workload("dsReadSpecialChars", "Special chars in partition values") { w =>
  w.sql("""CREATE TABLE tbl (id INT, category STRING) USING delta
    PARTITIONED BY (category)
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'hello world'),(2,'foo=bar'),(3,'a/b'),(4,'c%20d')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "category = 'hello world'")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadStringFilter: string equality filter
// ---------------------------------------------------------------------------
workload("dsReadStringFilter", "String equality filter") { w =>
  w.sql("""CREATE TABLE tbl (id INT, fruit STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'apple'),(2,'banana'),(3,'cherry'),(4,'apple'),(5,'date')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "fruit = 'apple'")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadTimestampType: timestamp column
// ---------------------------------------------------------------------------
workload("dsReadTimestampType", "Timestamp type") { w =>
  w.sql("""CREATE TABLE tbl (id INT, event_time TIMESTAMP) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1, TIMESTAMP'2024-01-15 10:30:00')")
  w.sql("INSERT INTO tbl VALUES (2, TIMESTAMP'2024-06-20 22:59:59')")
  w.sql("INSERT INTO tbl VALUES (3, TIMESTAMP'2024-12-31 00:00:00')")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadUpdateThenRead: UPDATE then read
// ---------------------------------------------------------------------------
workload("dsReadUpdateThenRead", "Read after UPDATE") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 11)")
  w.sql("UPDATE tbl SET value = value + 100 WHERE value <= 5")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "value > 100")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadVersionNegative: error - negative version
// ---------------------------------------------------------------------------
workload("dsReadVersionNegative", "Error: negative version", "error") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 6)")
  val t = w.table("tbl")
  w.snapshot(t, version = -1)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadVersionOutOfRange: error - version out of range
// ---------------------------------------------------------------------------
workload("dsReadVersionOutOfRange", "Error: version out of range", "error") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 6)")
  val t = w.table("tbl")
  w.snapshot(t, version = 100)
}

// ---------------------------------------------------------------------------
// dsReadVersionZero: time travel to v0
// ---------------------------------------------------------------------------
workload("dsReadVersionZero", "Time travel to version 0") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 6)")
  w.sql("INSERT INTO tbl SELECT id FROM range(6, 11)")
  w.sql("INSERT INTO tbl SELECT id FROM range(11, 16)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, version = 0)
  w.read(t, version = 1)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadWithAlias: simple read (alias is a Spark concept, table is normal)
// ---------------------------------------------------------------------------
workload("dsReadWithAlias", "Read with alias") { w =>
  w.sql("""CREATE TABLE tbl (id INT, name STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'alpha'),(2,'beta'),(3,'gamma')")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadWithLimit: read all (LIMIT is a Spark concept)
// ---------------------------------------------------------------------------
workload("dsReadWithLimit", "Read with limit") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 21)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadWithOrderBy: read all (ORDER BY is a Spark concept)
// ---------------------------------------------------------------------------
workload("dsReadWithOrderBy", "Read with order by") { w =>
  w.sql("""CREATE TABLE tbl (id INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (5),(3),(1),(4),(2)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dsReadWithPredicate: simple predicate pushdown
// ---------------------------------------------------------------------------
workload("dsReadWithPredicate", "Predicate pushdown") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 21)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "value > 5")
  w.snapshot(t)
}

// ===========================================================================
// dse* workloads (Delta Suite Extended)
// ===========================================================================

// ---------------------------------------------------------------------------
// dseReadAfterAlterTable: SET TBLPROPERTIES then append
// ---------------------------------------------------------------------------
workload("dseReadAfterAlterTable", "Read after ALTER TABLE SET TBLPROPERTIES") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 11)")
  w.sql("ALTER TABLE tbl SET TBLPROPERTIES ('delta.appendOnly' = 'true')")
  w.sql("INSERT INTO tbl SELECT id FROM range(11, 16)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dseReadAfterSchemaChange: ADD COLUMN then insert with new column
// ---------------------------------------------------------------------------
workload("dseReadAfterSchemaChange", "Read after schema change") { w =>
  w.sql("""CREATE TABLE tbl (id INT, name STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'alpha'),(2,'beta')")
  w.sql("ALTER TABLE tbl ADD COLUMN score DOUBLE")
  w.sql("INSERT INTO tbl VALUES (3,'gamma',99.9)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "score IS NOT NULL")
  w.read(t, predicate = "score IS NULL")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dseReadLargeFile: 10000-row table
// ---------------------------------------------------------------------------
workload("dseReadLargeFile", "Large file read") { w =>
  w.sql("""CREATE TABLE tbl (id BIGINT, data STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id, 'payload' FROM range(10000)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "id < 100")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dseReadSmallFiles: 10 single-row appends
// ---------------------------------------------------------------------------
workload("dseReadSmallFiles", "Many small files") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  (1 to 10).foreach { i =>
    w.sql(s"INSERT INTO tbl VALUES ($i)")
  }
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dseReadRepartitioned: 100 rows written (repartition is Spark concept)
// ---------------------------------------------------------------------------
workload("dseReadRepartitioned", "Repartitioned read") { w =>
  w.sql("""CREATE TABLE tbl (id BIGINT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(100)")
  val t = w.table("tbl")
  w.read(t)
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dseReadWithColumnPruning: column pruning / projection
// ---------------------------------------------------------------------------
workload("dseReadWithColumnPruning", "Column pruning") { w =>
  w.sql("""CREATE TABLE tbl (id INT, name STRING, score DOUBLE, active BOOLEAN) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl VALUES (1,'alpha',10.0,true),(2,'beta',20.0,false),(3,'gamma',30.0,true)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, columns = Seq("id", "name"))
  w.read(t, columns = Seq("score"))
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dseReadWithStats: 5 batches of 3 rows for stats-based filtering
// ---------------------------------------------------------------------------
workload("dseReadWithStats", "Read with stats-based filtering") { w =>
  w.sql("""CREATE TABLE tbl (id INT, batch STRING) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  // 5 separate appends so each batch lands in its own file (for stats skipping)
  w.sql("INSERT INTO tbl VALUES (1,'batch0'),(2,'batch0'),(3,'batch0')")
  w.sql("INSERT INTO tbl VALUES (101,'batch1'),(102,'batch1'),(103,'batch1')")
  w.sql("INSERT INTO tbl VALUES (201,'batch2'),(202,'batch2'),(203,'batch2')")
  w.sql("INSERT INTO tbl VALUES (301,'batch3'),(302,'batch3'),(303,'batch3')")
  w.sql("INSERT INTO tbl VALUES (401,'batch4'),(402,'batch4'),(403,'batch4')")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, predicate = "id = 1")
  w.read(t, predicate = "id >= 201 AND id <= 203")
  w.snapshot(t)
}

// ---------------------------------------------------------------------------
// dseSnapshotVersion: time travel across 3 versions
// ---------------------------------------------------------------------------
workload("dseSnapshotVersion", "Snapshot version read") { w =>
  w.sql("""CREATE TABLE tbl (value INT) USING delta
    TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
  w.sql("INSERT INTO tbl SELECT id FROM range(1, 6)")
  w.sql("INSERT INTO tbl SELECT id FROM range(6, 11)")
  w.sql("INSERT INTO tbl SELECT id FROM range(11, 16)")
  val t = w.table("tbl")
  w.read(t)
  w.read(t, version = 0)
  w.read(t, version = 1)
  w.read(t, version = 2)
  w.snapshot(t)
}

generateAll(
  sys.env.getOrElse("WORKLOAD_OUTPUT_DIR", "/tmp/workloads"),
  force = sys.env.getOrElse("WORKLOAD_FORCE", "false").toBoolean)
System.exit(0)
