new WorkloadSuite("identity_columns") {

  // -- ic_001_various_config: identity with start=1000, step=100 --
  test("ic_001_various_config", "Read identity with various start/step configurations", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 100),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (10)")
    w.sql("INSERT INTO tbl (value) VALUES (20)")
    w.sql("INSERT INTO tbl (value) VALUES (30)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "id >= 1000 AND id <= 1200")
    w.read(t, columns = Seq("id"))
    w.snapshot(t)
  }

  // -- ic_002_default_config: default identity (start=1, step=1) --
  test("ic_002_default_config", "Read identity with default configuration", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (100)")
    w.sql("INSERT INTO tbl (value) VALUES (200)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "id = 1")
    w.snapshot(t)
  }

  // -- ic_003_multiple_identity_cols: two identity columns --
  test("ic_003_multiple_identity_cols", "Multiple identity columns", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id1 LONG GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      id2 LONG GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY -10),
      value STRING
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (id1, id2, value) VALUES (1, 100, 'a')")
    w.sql("INSERT INTO tbl (value) VALUES ('b')")
    w.sql("INSERT INTO tbl (id1, value) VALUES (2, 'c')")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "id2 < 100")
    w.read(t, columns = Seq("id1", "id2"))
    w.snapshot(t)
  }

  // -- ic_004_with_generated_col: identity + generated column --
  test("ic_004_with_generated_col", "Identity column with generated column", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),
      id_plus_one LONG GENERATED ALWAYS AS (id + 1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (10)")
    w.sql("INSERT INTO tbl (value) VALUES (20)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, columns = Seq("id", "id_plus_one"))
    w.snapshot(t)
  }

  // -- ic_005_identity_not_exposed: partitioned, explicit insert --
  test("ic_005_identity_not_exposed", "Identity with explicit insert on partitioned table", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      part LONG,
      value INT
    ) USING delta PARTITIONED BY (part)
      TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (id, part, value) VALUES (1, 1, 10)")
    w.sql("INSERT INTO tbl (part, value) VALUES (2, 20)")
    w.sql("INSERT INTO tbl (id, part, value) VALUES (3, 1, 30)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "part = 1")
    w.read(t, columns = Seq("id", "part", "value"))
    w.snapshot(t)
  }

  // -- ic_006_ctas_no_inherit: CTAS does not inherit identity --
  test("ic_006_ctas_no_inherit", "CTAS does not inherit identity", "identityColumns") { w =>
    w.sql("""CREATE TABLE src (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO src (value) VALUES (10)")
    w.sql("""CREATE TABLE tbl USING delta
      TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')
      AS SELECT * FROM src""")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, columns = Seq("id"))
    w.snapshot(t)
  }

  // -- ic_007_replace_resets_watermark: CREATE OR REPLACE resets watermark --
  test("ic_007_replace_resets_watermark", "REPLACE resets identity watermark", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (1)")
    w.sql("INSERT INTO tbl (value) VALUES (2)")
    w.sql("""CREATE OR REPLACE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 5000 INCREMENT BY 1),
      value STRING
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES ('new')")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, version = 2)
    w.snapshotHistory(t)
  }

  // -- ic_008_restore_positive_step: RESTORE preserves high watermark --
  test("ic_008_restore_positive_step", "RESTORE preserves identity watermark (positive step)", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 0 INCREMENT BY 1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    for (i <- 1 to 6) w.sql(s"INSERT INTO tbl (value) VALUES ($i)")
    w.sql("RESTORE TABLE tbl TO VERSION AS OF 3")
    w.sql("INSERT INTO tbl (value) VALUES (99)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, version = 3)
    w.snapshotHistory(t)
  }

  // -- ic_009_restore_negative_step: RESTORE with negative step --
  test("ic_009_restore_negative_step", "RESTORE preserves identity watermark (negative step)", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 0 INCREMENT BY -1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    for (i <- 1 to 6) w.sql(s"INSERT INTO tbl (value) VALUES ($i)")
    w.sql("RESTORE TABLE tbl TO VERSION AS OF 3")
    w.sql("INSERT INTO tbl (value) VALUES (99)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "id < 0")
    w.snapshotHistory(t)
  }

  // -- ic_010_restore_partitioned: RESTORE on partitioned identity table --
  test("ic_010_restore_partitioned", "RESTORE on partitioned identity table", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
      value INT
    ) USING delta PARTITIONED BY (value)
      TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (1),(2)")
    w.sql("INSERT INTO tbl (value) VALUES (3),(4)")
    w.sql("RESTORE TABLE tbl TO VERSION AS OF 1")
    w.sql("INSERT INTO tbl (value) VALUES (5),(6)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "value = 1")
    w.read(t, version = 1)
    w.snapshotHistory(t)
  }

  // -- ic_011_generated_by_default: explicit insert allowed --
  test("ic_011_generated_by_default", "GENERATED BY DEFAULT identity", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (10)")
    w.sql("INSERT INTO tbl (id, value) VALUES (999, 20)")
    w.sql("INSERT INTO tbl (value) VALUES (30)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "id = 999")
    w.snapshot(t)
  }

  // -- ic_012_time_travel: identity with time travel --
  test("ic_012_time_travel", "Identity columns with time travel", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (10)")
    w.sql("INSERT INTO tbl (value) VALUES (20)")
    w.sql("INSERT INTO tbl (value) VALUES (30)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, version = 1)
    w.read(t, version = 2)
    w.snapshotHistory(t)
  }

  // -- ic_013_column_mapping: identity with column mapping --
  test("ic_013_column_mapping", "Identity with column mapping", "identityColumns", "columnMapping") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      name STRING
    ) USING delta TBLPROPERTIES (
      'delta.columnMapping.mode' = 'name',
      'delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (name) VALUES ('alice')")
    w.sql("INSERT INTO tbl (name) VALUES ('bob')")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "name = 'alice'")
    w.snapshot(t)
  }

  // -- ic_014_delete: identity after DELETE --
  test("ic_014_delete", "Identity columns after DELETE", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (1)")
    w.sql("INSERT INTO tbl (value) VALUES (2)")
    w.sql("DELETE FROM tbl WHERE value = 1")
    w.sql("INSERT INTO tbl (value) VALUES (3)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, version = 2)
    w.snapshotHistory(t)
  }

  // -- ic_015_merge: identity after MERGE --
  test("ic_015_merge", "Identity columns after MERGE", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 2),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (10),(20),(30)")
    w.sql("CREATE TABLE src (value INT) USING delta")
    w.sql("INSERT INTO src VALUES (20),(40)")
    w.sql("""MERGE INTO tbl t USING src s ON t.value = s.value
      WHEN MATCHED THEN UPDATE SET value = s.value * 10
      WHEN NOT MATCHED THEN INSERT (value) VALUES (s.value)""")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, version = 1)
    w.snapshotHistory(t)
  }

  // -- ic_016_update_with_cdf: identity + CDF after UPDATE --
  test("ic_016_update_with_cdf", "Identity with CDF after UPDATE", "identityColumns", "cdf") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 0 INCREMENT BY 1),
      value INT
    ) USING delta TBLPROPERTIES (
      'delta.enableChangeDataFeed' = 'true',
      'delta.enableDeletionVectors' = 'true')""")
    for (i <- 1 to 6) w.sql(s"INSERT INTO tbl (value) VALUES (${i * 10})")
    w.sql("UPDATE tbl SET value = value + 100 WHERE id < 3")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "value >= 100")
    w.read(t, version = 6)
    w.snapshotHistory(t)
  }

  // -- ic_bigint_type: BIGINT identity with 100 rows --
  test("ic_bigint_type", "BIGINT identity column", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) SELECT CAST(id AS INT) FROM range(100)")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "value >= 50")
    w.snapshot(t)
  }

  // -- ic_negative_step: identity with negative step --
  test("ic_negative_step", "Identity with negative step", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY -1),
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (10),(20),(30)")
    val t = w.table("tbl")
    w.read(t)
    w.snapshot(t)
  }

  // -- ic_partitioned: partitioned identity table --
  test("ic_partitioned", "Partitioned table with identity column", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT,
      category STRING
    ) USING delta PARTITIONED BY (category)
      TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value, category) VALUES (10,'A'),(20,'B'),(30,'A'),(40,'B'),(50,'A')")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "category = 'A'")
    w.read(t, predicate = "category = 'B'")
    w.snapshot(t)
  }

  // -- ic_with_schema_evolution: identity after ADD COLUMN --
  test("ic_with_schema_evolution", "Identity with schema evolution", "identityColumns") { w =>
    w.sql("""CREATE TABLE tbl (
      id LONG GENERATED ALWAYS AS IDENTITY,
      value INT
    ) USING delta TBLPROPERTIES ('delta.enableDeletionVectors' = 'true')""")
    w.sql("INSERT INTO tbl (value) VALUES (10),(20)")
    w.sql("ALTER TABLE tbl ADD COLUMN (extra STRING)")
    w.sql("INSERT INTO tbl (value, extra) VALUES (30, 'hello'),(40, 'world')")
    val t = w.table("tbl")
    w.read(t)
    w.read(t, predicate = "extra IS NOT NULL")
    w.read(t, version = 1)
    w.snapshotHistory(t)
  }

}.runAll()
